Assignment 1 : Data Exploration and Cleaning Using Pandas

Importing required libraries

In [4]:
import pandas as pd
import numpy as np

Loading the CSV dataset

In [5]:
df = pd.read_csv("shirts.csv")

In [6]:
print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

[link text](https://)Displaying the first 5 rows

In [7]:
display(df.head())

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18719236,SPYKAR,Men Blue Slim Fit Faded Casual Shirt,2.9,12,2999.0,50.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/187...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",SPY███ LI███TYL█████████E L█████████,"[{""size"":""38"",""value"":""38.0in"",""value_name"":""C...",NaN,19t███loo███F W█████████s C███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
1,18960048,The Indian Garage Co,Men White & Beige Striped Casual Shirt,4.2,128,1749.0,74.0,"""₹507.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":8,""2_stars"":3,""3_stars"":14,""4_stars""...","[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,1 s███loo███Cab█████████-01███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
2,18960188,The Indian Garage Co,Men White & Charcoal Grey Printed Cotton Casua...,4.4,35,1749.0,74.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
3,18960016,The Indian Garage Co,Men Cream-Coloured Solid Casual Shirt,4.0,102,1749.0,74.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":8,""2_stars"":9,""3_stars"":11,""4_stars""...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
4,18996778,U.S. Polo Assn.,U S Polo Assn Men Blue Gingham Checks Patch Po...,4.2,10,2599.0,50.0,"""₹1,559.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""38"",""value"":""39.5in"",""value_name"":""C...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts

Displaying the last 5 rows

In [8]:
display(df.tail())

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
92,20308620,Arrow,Men Blue Original Slim Fit Grid Tattersall Che...,4.0,59,2499.0,50.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/203...,...,"{""1_star"":6,""2_stars"":1,""3_stars"":11,""4_stars""...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""38"",""value"":""41.73in"",""value_name"":""...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
93,18960194,The Indian Garage Co,Men White Printed Casual Cotton Shirt,3.9,73,1749.0,72.0,"""₹349.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":8,""2_stars"":4,""3_stars"":11,""4_stars""...","[{""percentage"":""83"",""value_name"":""Fit, Just Ri...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
94,19276504,Turtle,Men Beige Printed Cotton Slim Fit Casual Shirt,4.7,7,1399.0,40.0,"""₹839.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, A Littl...",Tur███ Li███ed,"[{""size"":""39"",""value"":""43.0in"",""value_name"":""C...",NaN,Lem███Fre███ Bl█████████d F███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
95,19299798,Louis Philippe,Men Navy Blue Solid Slim Fit Formal Shirt,4.4,32,2799.0,NaN,"""₹2,519.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Ret███Net███,"[{""size"":""39"",""value"":""44.15in"",""value_name"":""...",NaN,Blo███B-1███abi█████████-24███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
96,18903374,Levis,Women Blue Pure Cotton Casual Shirt,4.6,168,2599.0,45.0,"""₹2,079.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":7,""2_stars"":2,""3_stars"":8,""4_stars"":...",NaN,Vis███ St███,"[{""size"":""XS"",""value"":""35.5in"",""value_name"":""B...",NaN,3rd███oor███o. █████████Mai███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts

Displaying the dataset shape

In [9]:
print(df.shape)

(97, 24)

Displaying column names

In [10]:
print(df.columns.tolist())

['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

Displaying data types

In [11]:
print(df.dtypes)

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

Displaying dataset information

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              97 non-null     int64
 1   title                   97 non-null     object
 2   product_description     97 non-null     object
 3   rating                  97 non-null     float64
 4   ratings_count           97 non-null     int64
 5   initial_price           97 non-null     float64
 6   discount                87 non-null     float64
 7   final_price             97 non-null     object
 8   currency                97 non-null     object
 9   images                  97 non-null     object
 10  delivery_options        97 non-null     object
 11  product_details         97 non-null     object
 12  breadcrumbs             97 non-null     object
 13  product_specifications  97 non-null     object
 14  amount_of_stars         97 non-null     object
 15  what_customers_said     63 non-null     object
 16  seller_name             67 non-null     object
 17  sizes                   97 non-null     object
 18  videos                  10 non-null     object
 19  seller_information      67 non-null     object
 20  variations              27 non-null     object
 21  best_offer              97 non-null     object
 22  more_offers             97 non-null     object
 23  category                97 non-null     object
dtypes: float64(3), int64(2), object(19)
memory usage: 18.3+ KB

Displaying statistical summary

In [13]:
display(df.describe(include='all'))

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
count,9.700000e+01,97,97,97.000000,97.000000,97.00000,87.000000,97,97,97,...,97,63,67,97,10,67,27,97,97,97
unique,NaN,47,97,NaN,NaN,NaN,NaN,65,1,97,...,94,40,32,61,10,32,9,58,41,1
top,NaN,The Indian Garage Co,Men Blue Slim Fit Faded Casual Shirt,NaN,NaN,NaN,NaN,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/187...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",IND███ NE███E P█████████MIT███,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...","[""rw-13621622_cae700"",""https://videos.myntasse...","HOU███NO.███ GR█████████R, ███████████████████...",[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
freq,NaN,10,1,NaN,NaN,NaN,NaN,5,97,1,...,3,19,8,9,1,8,9,32,32,97
mean,1.763930e+07,NaN,NaN,3.967010,62.731959,2233.43299,55.873563,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2.081964e+06,NaN,NaN,0.813009,143.576237,952.24174,14.212511,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.345325e+07,NaN,NaN,0.000000,0.000000,799.00000,14.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.730031e+07,NaN,NaN,3.900000,11.000000,1749.00000,50.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.735674e+07,NaN,NaN,4.100000,23.000000,1999.00000,55.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.896015e+07,NaN,NaN,4.400000,68.000000,2499.00000,70.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2.232656e+07,NaN,NaN,4.900000,1246.000000,6999.00000,80.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Identifying missing values

In [14]:
print(df.isnull().sum())

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                  10
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       34
seller_name               30
sizes                      0
videos                    87
seller_information        30
variations                70
best_offer                 0
more_offers                0
category                   0
dtype: int64

Filling missing discount values with 0

In [15]:
if 'discount' in df.columns:
    df['discount'] = df['discount'].fillna(0)

Defining columns to drop

In [16]:
columns_to_drop = [
    'videos',
    'variations',
    'what_customers_said',
    'seller_name',
    'seller_information'
]

Dropping columns with excessive missing data

In [17]:
df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

Missing values after handling

In [18]:
print(df.isnull().sum())

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
sizes                     0
best_offer                0
more_offers               0
category                  0
dtype: int64

Converting final_price to numeric format

In [19]:
if 'final_price' in df.columns:
    df['final_price'] = (
        df['final_price']
        .astype(str)
        .str.replace('₹', '', regex=False)
        .str.replace(',', '', regex=False)
        .str.replace('"', '', regex=False)
    )
    df['final_price'] = pd.to_numeric(
        df['final_price'],
        errors='coerce'
    )
    df.dropna(subset=['final_price'], inplace=True)

Displaying final_price data type

In [20]:
print(df['final_price'].dtype)

float64

Selecting specific columns

In [21]:
selected_columns = [
    col for col in ['title', 'rating', 'final_price']
    if col in df.columns
]
display(df[selected_columns].head())

                  title  rating  final_price
0                SPYKAR     2.9       1499.0
1  The Indian Garage Co     4.2        507.0
2  The Indian Garage Co     4.4        454.0
3  The Indian Garage Co     4.0        454.0
4       U.S. Polo Assn.     4.2       1559.0

Filtering products with rating greater than 0

In [22]:
if 'rating' in df.columns:
    filtered_df = df[df['rating'] > 0]
    print("Filtered Shape:", filtered_df.shape)
    df = filtered_df
    display(filtered_df.head())

Filtered Shape: (94, 19)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,sizes,best_offer,more_offers,category
0,18719236,SPYKAR,Men Blue Slim Fit Faded Casual Shirt,2.9,12,2999.0,50.0,1499.0,INR,http://assets.myntassets.com/assets/images/187...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Blue faded opaque Casual shirt...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":6,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""38"",""value"":""38.0in"",""value_name"":""C...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
1,18960048,The Indian Garage Co,Men White & Beige Striped Casual Shirt,4.2,128,1749.0,74.0,507.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""White & beige striped opaque C...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":8,""2_stars"":3,""3_stars"":14,""4_stars""...","[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
2,18960188,The Indian Garage Co,Men White & Charcoal Grey Printed Cotton Casua...,4.4,35,1749.0,74.0,454.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""White & Charcoal grey typograp...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
3,18960016,The Indian Garage Co,Men Cream-Coloured Solid Casual Shirt,4.0,102,1749.0,74.0,454.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Cream-coloured solid opaque Ca...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":8,""2_stars"":9,""3_stars"":11,""4_stars""...","[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
4,18996778,U.S. Polo Assn.,U S Polo Assn Men Blue Gingham Checks Patch Po...,4.2,10,2599.0,50.0,1559.0,INR,http://assets.myntassets.com/assets/images/189...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Blue gingham checks checked op...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""size"":""38"",""value"":""39.5in"",""value_name"":""C...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts

Removing duplicate product entries

In [23]:
rows_before = len(df)
if 'product_id' in df.columns:
    df.drop_duplicates(subset=['product_id'], inplace=True)
else:
    df.drop_duplicates(inplace=True)
rows_after = len(df)
print("Rows Before:", rows_before)
print("Rows After :", rows_after)
print("Duplicates Removed:", rows_before - rows_after)

Rows Before: 94
Rows After : 94
Duplicates Removed: 0

Setting random seed for quantity generation

In [24]:
np.random.seed(42)

Generating a sample quantity column

In [25]:
df['quantity'] = np.random.randint(
    1,
    6,
    size=len(df)
)

Calculating total amount

In [26]:
df['total_amount'] = (
    df['final_price']
    * df['quantity']
)

Displaying derived columns

In [27]:
display(
    df[
        ['final_price',
         'quantity',
         'total_amount']
    ].head()
)

   final_price  quantity  total_amount
0       1499.0         4        5996.0
1        507.0         5        2535.0
2        454.0         3        1362.0
3        454.0         5        2270.0
4       1559.0         5        7795.0

Displaying cleaned data preview

In [28]:
display(df.head())

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_details,breadcrumbs,product_specifications,amount_of_stars,sizes,best_offer,more_offers,category,quantity,total_amount
0,18719236,SPYKAR,Men Blue Slim Fit Faded Casual Shirt,2.9,12,2999.0,50.0,1499.0,INR,http://assets.myntassets.com/assets/images/187...,...,"{""description"":""Blue faded opaque Casual shirt...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":6,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""size"":""38"",""value"":""38.0in"",""value_name"":""C...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts,4,5996.0
1,18960048,The Indian Garage Co,Men White & Beige Striped Casual Shirt,4.2,128,1749.0,74.0,507.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""description"":""White & beige striped opaque C...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":8,""2_stars"":3,""3_stars"":14,""4_stars""...","[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts,5,2535.0
2,18960188,The Indian Garage Co,Men White & Charcoal Grey Printed Cotton Casua...,4.4,35,1749.0,74.0,454.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""description"":""White & Charcoal grey typograp...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts,3,1362.0
3,18960016,The Indian Garage Co,Men Cream-Coloured Solid Casual Shirt,4.0,102,1749.0,74.0,454.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""description"":""Cream-coloured solid opaque Ca...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":8,""2_stars"":9,""3_stars"":11,""4_stars""...","[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts,5,2270.0
4,18996778,U.S. Polo Assn.,U S Polo Assn Men Blue Gingham Checks Patch Po...,4.2,10,2599.0,50.0,1559.0,INR,http://assets.myntassets.com/assets/images/189...,...,"{""description"":""Blue gingham checks checked op...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""size"":""38"",""value"":""39.5in"",""value_name"":""C...","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts,5,7795.0

Displaying final data shape

In [29]:
print(df.shape)

(94, 21)

Saving the cleaned dataset to a CSV file

In [30]:
output_file = "cleaned_shopping_dataset.csv"

In [31]:
df.to_csv(
    output_file,
    index=False
)

In [32]:
print(
    f"Cleaned dataset saved as: {output_file}"
)

Cleaned dataset saved as: cleaned_shopping_dataset.csv

Downloading the cleaned dataset

In [33]:
from google.colab import files

In [34]:
files.download(output_file)